### ISSUE TITLE
Conceptual bug!!

### ISSUE THREAD

**Issue by rash1993** [kevinzakka/spatial_transformer_network#3]
Hi,

In the script main.py, it's cool that you input the output of the localization network to the spatial transformer to obtain the transformed image as h_trans. But, post that you are providing the initial (original/untransformed) image to the convolutional network. Should not it be the transformed image (h_trans) that should go through the CNN? 

I trained the model over the complete dataset (using the script as it is), but the transformations learned are not what expected. It seems to be random! Which is justified in the current scenario as the localization is not part of the optimization routine!

**Comment by kevinzakka** [comment]
Hey man, you're absolutely right. I haven't taken a look at the repo in a long time, and never updated it to the last version I had locally due to breaking tensorflow changes that happened a few months ago. I'll fix the error, but also need to take a look at whatever broke in the update as well.

Thanks for spotting that though :)

**Comment by rash1993** [comment]
I don't think there are many changes needed, as far as the latest version of the tensorflow is concerned! Anyways, it is a useful repository! Thanks! :)

**Comment by kevinzakka** [comment]
No worries, feel free to open this up if you find any more issues. 

Cheers
